# Generated by Django 4.1.1 on 2022-10-13 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ArtistId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=70)),
                ('City', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=40)),
                ('County', models.CharField(max_length=40)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=24)),
                ('Fax', models.CharField(max_length=24)),
                ('Email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeeId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('GenreId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('InvoiceId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media_types',
            fields=[
                ('MediaTypeId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('PlaylistId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('TrackId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Composer', models.CharField(max_length=220)),
                ('GenresId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.genres')),
                ('MediaTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.media_types')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaylistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.playlists')),
                ('TrackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices_items',
            fields=[
                ('InvoiceItemId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('InvoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.invoices')),
                ('TrackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('AlbumId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=160)),
                ('ArtistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.artists')),
            ],
        ),
    ]
