# Generated by Django 4.1.2 on 2022-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='MediaTypes',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='InvoicesItems',
            new_name='InvoicesItem',
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='MediaType',
        ),
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
