# Generated by Django 4.1.2 on 2022-10-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0002_rename_albums_album_rename_mediatypes_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='support_rep_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kAboom.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='fax',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kAboom.mediatype'),
        ),
    ]
