# Generated by Django 4.1.2 on 2022-10-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0004_employee_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bytes',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='track',
            name='miliseconds',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='track',
            name='until_price',
            field=models.FloatField(default=None),
        ),
    ]
