# Generated by Django 4.1.2 on 2022-10-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0005_track_bytes_track_miliseconds_track_until_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='miliseconds',
            new_name='milliseconds',
        ),
    ]
