# Generated by Django 4.1.2 on 2022-10-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0006_rename_miliseconds_track_milliseconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(default=None, max_length=220),
        ),
    ]
