# Generated by Django 4.1.2 on 2022-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0008_alter_track_composer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
