# Generated by Django 4.1.2 on 2022-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0011_alter_employee_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
