# Generated by Django 4.1.2 on 2022-10-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0013_alter_customer_support_rep_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='support_rep_id',
            new_name='support_rep',
        ),
    ]
