# Generated by Django 4.1.2 on 2022-10-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0014_rename_support_rep_id_customer_support_rep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='county',
            new_name='country',
        ),
    ]
