# Generated by Django 4.1.2 on 2022-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0016_alter_customer_company_alter_customer_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
