# Generated by Django 4.1.2 on 2022-10-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0017_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_adress',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_postal_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_state',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inovice_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='invoicesitem',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='invoicesitem',
            name='unit_price',
            field=models.IntegerField(default=None),
        ),
    ]
