# Generated by Django 4.1.2 on 2022-10-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0018_invoice_billing_adress_invoice_billing_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billing_adress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='inovice_date',
            new_name='invoice_date',
        ),
    ]
