# Generated by Django 4.1.3 on 2022-11-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kAboom', '0019_rename_billing_adress_invoice_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('albums', models.ManyToManyField(to='kAboom.album')),
                ('artists', models.ManyToManyField(to='kAboom.artist')),
                ('playlists', models.ManyToManyField(to='kAboom.playlist')),
                ('tracks', models.ManyToManyField(to='kAboom.track')),
            ],
        ),
    ]
