# Generated by Django 4.1.3 on 2022-11-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0020_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tracks',
        ),
    ]
