# Generated by Django 4.1.3 on 2022-11-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0021_remove_userprofile_albums_remove_userprofile_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite',
            field=models.ManyToManyField(to='kAboom.userprofile'),
        ),
        migrations.AddField(
            model_name='artist',
            name='favorite',
            field=models.ManyToManyField(to='kAboom.userprofile'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='favorite',
            field=models.ManyToManyField(to='kAboom.userprofile'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='kAboom.userprofile'),
        ),
        migrations.AddField(
            model_name='track',
            name='favorite',
            field=models.ManyToManyField(to='kAboom.userprofile'),
        ),
    ]
