# Generated by Django 4.1.3 on 2022-11-29 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kAboom', '0022_album_favorite_artist_favorite_playlist_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
