# Generated by Django 3.2 on 2022-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0022_album_favorite_artist_favorite_playlist_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(default=None, max_length=100, verbose_name='test'),
        ),
    ]
