# Generated by Django 4.1.3 on 2022-11-29 22:23

from django.db import migrations


def data_migrate_user(apps, schema_editor):
    Playlist = apps.get_model('kAboom', 'Playlist')
    for playlist in Playlist.objects.all():
        playlist.user_maker = '%s' % playlist.maker
        playlist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0023_playlist_user_maker'),
    ]

    operations = [
        migrations.RunPython(data_migrate_user)
    ]
