# Generated by Django 4.1.3 on 2022-11-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0024_auto_20221130_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='maker',
        ),
    ]
