# Generated by Django 4.1.3 on 2022-12-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0025_remove_playlist_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_of_theme',
            field=models.BooleanField(default=False),
        ),
    ]
