# Generated by Django 4.1.3 on 2022-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0026_userprofile_type_of_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_theme',
            field=models.CharField(choices=[('D', 'Freshman'), ('L', 'Sophomore')], default='D', max_length=1),
        ),
    ]
