# Generated by Django 4.1.3 on 2022-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0027_alter_userprofile_type_of_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_theme',
            field=models.CharField(choices=[('D', 'Dark'), ('L', 'Light')], default='D', max_length=7),
        ),
    ]
