# Generated by Django 4.1.3 on 2022-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0030_auto_20221216_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_of_theme',
            field=models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='DARK', max_length=7),
        ),
    ]
