# Generated by Django 4.1.3 on 2023-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0031_alter_userprofile_type_of_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='kAboom.genre'),
        ),
    ]
