# Generated by Django 4.1.3 on 2023-01-23 07:15

from django.db import migrations
from kAboom.models import Track


def data_track_genres(apps, schema_editor):
    Track = apps.get_model('kAboom', 'Track')
    Genre = apps.get_model('kAboom', 'Genre')
    for track in Track.objects.all():
        genre = Genre.objects.get(id=track.genre_id)
        track.genres.add(genre)
        track.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0032_track_genres'),
        # ('kAboom', '0002_rename_albums_album_rename_mediatypes_artist_and_more.py'),
    ]

    operations = [
        migrations.RunPython(data_track_genres)
    ]
