# Generated by Django 4.1.3 on 2023-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0033_auto_20230123_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(to='kAboom.genre'),
        ),
    ]
