# Generated by Django 4.1.3 on 2023-01-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0034_remove_track_genre_alter_track_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genres',
            new_name='genre',
        ),
    ]
