# Generated by Django 4.1.3 on 2023-01-30 09:04

from django.db import migrations


def data_migrate_track_artist(apps, schema_editor):
    Track = apps.get_model('kAboom', 'Track')
    for track in Track.objects.all():
        if not track.artist:
            track.artist = track.album.artist
            track.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0037_track_artist'),

    ]

    operations = [
        migrations.RunPython(data_migrate_track_artist)
    ]