# Generated by Django 4.1.3 on 2023-02-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kAboom', '0040_parser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenresTags',
            new_name='GenreTag',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='genre_tags',
            new_name='genre_tag',
        ),
    ]
